# Generated by Django 6.0.1 on 2026-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=200, verbose_name='Имя')),
                ('middle_name', models.CharField(help_text='Введите ваше отчество', max_length=200, verbose_name='Отчество')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ('last_name', 'name', 'email'),
            },
        ),
    ]
