# Generated by Django 6.0.2 on 2026-02-19 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_mailrecipient_views_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Напишите тему письма', max_length=70, verbose_name='Тема сообщения')),
                ('message', models.TextField(blank=True, help_text='Напишите сообщение', max_length=5000, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Сообщение')),
            ],
        ),
        migrations.AlterField(
            model_name='mailrecipient',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
    ]
