# Generated by Django 6.0.2 on 2026-02-25 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_mailrecipient_is_active_mailrecipient_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="attempt_time",
            new_name="timestamp",
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Ошибка")],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.DeleteModel(
            name="MailingLog",
        ),
    ]
