# Generated by Django 6.0.2 on 2026-02-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_message_alter_mailrecipient_views_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=20, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.message', verbose_name='Сообщение')),
                ('recipients', models.ManyToManyField(to='web_app.mailrecipient', verbose_name='Получатели')),
            ],
        ),
    ]
