# Generated by Django 6.0.2 on 2026-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0005_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="timestamp",
            new_name="attempt_time",
        ),
    ]
