# Generated by Django 6.0.2 on 2026-02-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0006_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
